### Group Number : 8
### Roll Numbers :
22CS60R70 - YASH PANELIYA

22CS60R04 - SAYAK ROY

18EC3AI19 - RAVI KARTHIK
### Project Number : SESVM
### Project Title : Spam Email Classification using Support Vector Machine

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from cvxopt import matrix, solvers
import cvxopt
from sklearn.metrics import classification_report, accuracy_score
from sklearn.decomposition import PCA

## Pre-processing the data:

i. Randomly pick 70% of the data as a training set and the rest as a test set.

ii. Normalize each feature of the dataset to have zero mean and unit variance. Note that while normalizing the features, their mean and variance should be computed over the train split only. Once, the mean and variance are computed using only the train split, you normalize the test split using the mean and variance computed over the train split.

In [2]:
df = pd.read_csv('./spambase.data', header=None)
df

,0,1,2,3,4,5,6,7,8,9,...,48,49,50,51,52,53,54,55,56,57
0,0.00,0.64,0.64,0.0,0.32,0.00,0.00,0.00,0.00,0.00,...,0.000,0.000,0.0,0.778,0.000,0.000,3.756,61,278,1
1,0.21,0.28,0.50,0.0,0.14,0.28,0.21,0.07,0.00,0.94,...,0.000,0.132,0.0,0.372,0.180,0.048,5.114,101,1028,1
2,0.06,0.00,0.71,0.0,1.23,0.19,0.19,0.12,0.64,0.25,...,0.010,0.143,0.0,0.276,0.184,0.010,9.821,485,2259,1
3,0.00,0.00,0.00,0.0,0.63,0.00,0.31,0.63,0.31,0.63,...,0.000,0.137,0.0,0.137,0.000,0.000,3.537,40,191,1
4,0.00,0.00,0.00,0.0,0.63,0.00,0.31,0.63,0.31,0.63,...,0.000,0.135,0.0,0.135,0.000,0.000,3.537,40,191,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4596,0.31,0.00,0.62,0.0,0.00,0.31,0.00,0.00,0.00,0.00,...,0.000,0.232,0.0,0.000,0.000,0.000,1.142,3,88,0
4597,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,...,0.000,0.000,0.0,0.353,0.000,0.000,1.555,4,14,0
4598,0.30,0.00,0.30,0.0,0.00,0.00,0.00,0.00,0.00,0.00,...,0.102,0.718,0.0,0.000,0.000,0.000,1.404,6,118,0
4599,0.96,0.00,0.00,0.0,0.32,0.00,0.00,0.00,0.00,0.00,...,0.000,0.057,0.0,0.000,0.000,0.000,1.147,5,78,0
4600,0.00,0.00,0.65,0.0,0.00,0.00,0.00,0.00,0.00,0.00,...,0.000,0.000,0.0,0.125,0.000,0.000,1.250,5,40,0

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [3]:
# Calculating NULL percentage in each feature
((df.isnull().sum() / len(df))*100).sort_values(ascending=False).to_frame()

      0
0   0.0
43  0.0
31  0.0
32  0.0
33  0.0
34  0.0
35  0.0
36  0.0
37  0.0
38  0.0
39  0.0
40  0.0
41  0.0
42  0.0
44  0.0
1   0.0
45  0.0
46  0.0
47  0.0
48  0.0
49  0.0
50  0.0
51  0.0
52  0.0
53  0.0
54  0.0
55  0.0
56  0.0
30  0.0
29  0.0
28  0.0
27  0.0
2   0.0
3   0.0
4   0.0
5   0.0
6   0.0
7   0.0
8   0.0
9   0.0
10  0.0
11  0.0
12  0.0
13  0.0
14  0.0
15  0.0
16  0.0
17  0.0
18  0.0
19  0.0
20  0.0
21  0.0
22  0.0
23  0.0
24  0.0
25  0.0
26  0.0
57  0.0

In [4]:
# Randomize the order of rows in dataset
df = df.reindex(np.random.permutation(df.index)) 
df.head()

,0,1,2,3,4,5,6,7,8,9,...,48,49,50,51,52,53,54,55,56,57
519,0.31,0.00,0.00,0.0,0.00,0.0,0.00,0.0,0.0,0.00,...,0.114,0.0,0.000,0.057,0.0,0.000,2.972,18,110,1
662,0.00,0.28,0.84,0.0,0.28,0.0,0.14,0.0,0.0,0.42,...,0.000,0.0,0.000,0.583,0.0,0.067,5.415,132,991,1
4427,0.00,0.00,0.00,0.0,0.00,0.0,0.00,0.0,0.0,0.00,...,0.000,0.0,0.000,0.000,0.0,0.000,5.153,55,67,0
3790,0.00,0.00,0.00,0.0,1.61,0.0,0.00,0.0,0.0,0.00,...,0.000,0.0,0.144,0.000,0.0,0.000,1.913,13,44,0
3509,0.30,0.30,0.00,0.0,0.60,0.3,0.00,0.6,0.0,0.00,...,0.000,0.0,0.000,0.000,0.0,0.000,1.389,8,82,0

In [5]:
# reset the indices of df
df = df.reset_index(drop=True)

In [ ]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,48,49,50,51,52,53,54,55,56,57
0,0.0,0.00,0.29,0.0,0.88,0.14,0.0,0.00,0.88,0.0,...,0.0,0.097,0.000,0.388,0.048,0.024,2.264,49,428,1
1,0.0,0.00,0.00,0.0,2.22,0.00,0.0,0.00,0.00,0.0,...,0.0,0.000,0.000,0.000,0.000,0.000,1.000,1,22,0
2,0.0,0.00,0.00,0.0,1.88,0.00,0.0,1.88,0.00,0.0,...,0.0,0.206,0.000,0.000,0.000,0.000,2.450,11,49,1
3,0.0,0.00,0.00,0.0,0.00,0.00,0.0,0.00,0.00,0.0,...,0.0,0.000,0.265,0.000,0.000,0.000,1.650,12,33,0
4,0.0,2.07,0.00,0.0,0.00,0.00,0.0,0.00,1.55,0.0,...,0.0,0.070,0.000,0.000,0.141,0.211,25.812,104,413,0

In [6]:
# replacing 0 with -1 for easy calculations
# -1: Not spam
# 1: Spam
df[57] = df[57].replace(0,-1)
df[57] = df[57].astype(float)
df[57]

0       1.0
1       1.0
2      -1.0
3      -1.0
4      -1.0
       ...
4596   -1.0
4597   -1.0
4598   -1.0
4599    1.0
4600   -1.0
Name: 57, Length: 4601, dtype: float64

In [7]:
# Separating X and y
X = df.iloc[:, :-1].values
y = df.iloc[:, -1].values

# generating splitting indices for 70% separation
split_idx = int(0.7 * len(df))

In [8]:
# Splitting into train and test dataset
X_train = X[:split_idx]
X_test = X[split_idx:]
y_train = y[:split_idx]
y_test = y[split_idx:]

In [9]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(3220, 57)
(1381, 57)
(3220,)
(1381,)

In [10]:
# Standardize the features
mean = np.mean(X_train, axis=0)
std = np.std(X_train, axis=0)

X_train = (X_train - mean) / std

X_test = (X_test - mean) / std

## Training the model:

i. Note that training requires solving the dual optimization problem. To solve the dual optimization problem you can use any python packages like: CVXOPT or
Scipy.optimize.minimize

ii. Implement the following three kernels: (a) linear, (b) quadratic and (c) radial basis function

Making predictions: Write a function that takes new datapoint as input and predicts the
class

In [11]:
def linear_kernel(x1, x2):
    return np.dot(x1, x2)

def quadratic_kernel(x1,x2):
    return np.power(np.dot(x1, x2) + 1, 2)

def rbf_kernel(x1,x2, gamma = 0.3):
    norm = np.linalg.norm(x1 - x2)
    return np.exp(-gamma * norm**2)

class SVM(object):

    def __init__(self, kernel_type='linear', C=None):
        self.kernel_type = kernel_type
        if kernel_type=='linear':
          self.kernel = linear_kernel
        elif kernel_type == 'poly':
          self.kernel = quadratic_kernel
        else:
          self.kernel = rbf_kernel
        
        self.C = C
        if self.C is not None: self.C = float(self.C)

    def fit(self, X, y):
        n_samples, n_features = X.shape
        print("Number of samples: ", n_samples, " Number of features: ", n_features)

        # Gram matrix K[i, j] = K(x_i, x_j)
        K = np.zeros((n_samples, n_samples))
        for i in range(n_samples):
            for j in range(n_samples):
                K[i,j] = self.kernel(X[i], X[j])

        # Outer-product gives a matrix such that [i, j] = y_i * y_j
        # Element-wise multiplication gives P, such that:
        # P[i, j] = y_i * y_j * K(x_i, x_j)
        #
        # First factor of objective function:
        # 1/2 x^T P x = 1/2 * sum(alpha_i * alpha_j * y_i * y_j * K(x_i, x_j)
        P = cvxopt.matrix(np.outer(y, y) * K)

        # 2nd factor of objective function:
        # q^T x = -1 * sum(alpha)
        q = cvxopt.matrix(np.ones(n_samples) * -1)

        # Eq constraint (Ax = b): sum(alpha * y) = 0
        A = cvxopt.matrix(y, (1, n_samples))
        b = cvxopt.matrix(0.0)

        # Ineq constraint (Gx <= h):
        # alpha <= C and -alpha <= 0 (equivalent to alpha >= 0)
        if self.C is None:
            G = cvxopt.matrix(np.identity(n_samples) * -1)
            h = cvxopt.matrix(np.zeros(n_samples))
        else:
            tmp1 = np.identity(n_samples) * -1
            tmp2 = np.identity(n_samples)
            G = cvxopt.matrix(np.vstack((tmp1, tmp2)))
            tmp1 = np.zeros(n_samples)
            tmp2 = np.ones(n_samples) * self.C
            h = cvxopt.matrix(np.hstack((tmp1, tmp2)))

        cvxopt.solvers.options['show_progress'] = False
        # solve QP problem
        solution = cvxopt.solvers.qp(P, q, G, h, A, b)

        # Lagrange multipliers
        a = np.ravel(solution['x'])

        # Support vectors have non zero lagrange multipliers
        sv = a > 1e-5
        ind = np.arange(len(a))[sv]
        self.a = a[sv]
        self.sv = X[sv]
        self.sv_y = y[sv]
        print(f'{len(self.a)} support vectors out of {n_samples} points')

        # Intercept - average over indices where 0 < alpha_i < C
        self.b = 0
        alpha_diff_C_count = 0
        is_eq_to_C = lambda a: self.C is not None and a > self.C - 1e-5

        for n in range(len(self.a)):
            if is_eq_to_C(self.a[n]):
                continue

            alpha_diff_C_count += 1
            self.b += self.sv_y[n]
            self.b -= np.sum(self.a * self.sv_y * K[ind[n],sv])

        self.b = self.b / alpha_diff_C_count if alpha_diff_C_count > 0 else 0

        print("b: ", self.b)

        # Weight vector: we can't compute w if we are using a kernel
        # since the sum would be over alpha * y * phi(x), where
        # phi is the implicit mapping embedded in the kernel
        if self.kernel_type == 'linear':
            self.w = np.zeros(n_features)
            for n in range(len(self.a)):
                self.w += self.a[n] * self.sv_y[n] * self.sv[n]
        else:
            self.w = None

    # function to project the datapoint on plot
    def project(self, X):
        if self.w is not None:
            return np.dot(X, self.w) + self.b
        else:
            y_predict = np.zeros(len(X))
            for i in range(len(X)):
                s = 0
                for a, sv_y, sv in zip(self.a, self.sv_y, self.sv):
                    s += a * sv_y * self.kernel(X[i], sv)
                y_predict[i] = s
            return y_predict + self.b

    # function to predict label
    def predict(self, X):
        return np.sign(self.project(X))

Evaluation: Finally, you should generate results on the given data and compare its results with the sklearn module (sklearn.svm)

In [12]:
s = SVM(C=10, kernel_type='rbf')
s.fit(X_train, y_train)

y_pred=(s.predict(X_test))

print(classification_report(y_pred, y_test))

Number of samples:  3220  Number of features:  57
2608 support vectors out of 3220 points
b:  -0.21494059840855612
              precision    recall  f1-score   support

        -1.0       0.97      0.79      0.87       992
         1.0       0.64      0.93      0.76       389

    accuracy                           0.83      1381
   macro avg       0.80      0.86      0.82      1381
weighted avg       0.88      0.83      0.84      1381

Evaluation using sklearn library

In [13]:
from sklearn import svm
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

clf = svm.SVC(kernel='linear', C=1)
clf.fit(X_train, y_train)

# Predict on the test set
y_pred = clf.predict(X_test)

# Calculate accuracy
acc = accuracy_score(y_test, y_pred)
print(f"Accuracy (Linear): {acc}")

clf = svm.SVC(kernel='poly', C=1)
clf.fit(X_train, y_train)

# Predict on the test set
y_pred = clf.predict(X_test)

# Calculate accuracy
acc = accuracy_score(y_test, y_pred)
print(f"Accuracy (Quadratic): {acc}")

clf = svm.SVC(kernel='rbf', C=1)
clf.fit(X_train, y_train)

# Predict on the test set
y_pred = clf.predict(X_test)

# Calculate accuracy
acc = accuracy_score(y_test, y_pred)
print(f"Accuracy (RBF): {acc}")

Accuracy (Linear): 0.9268645908761767
Accuracy (Quadratic): 0.775524981897176
Accuracy (RBF): 0.9254163649529327

## Making predictions and evaluation

In [ ]:
from collections import defaultdict

# different C values
c_values = [1,10,100]
kernels = ['linear', 'poly', 'rbf']

model_acc = defaultdict(dict)
sklearn_acc = defaultdict(dict)

for c in c_values:
  for kernel in kernels:
    # running our model
    svmobj = SVM(C=c, kernel_type=kernel)
    svmobj.fit(X_train, y_train)
    y_pred=(svmobj.predict(X_test))
    model_acc[c][kernel] = accuracy_score(y_test, y_pred)

    # sklearn mode
    clf = svm.SVC(kernel=kernel, C=c)
    if kernel=='poly':
      clf = svm.SVC(kernel=kernel, C=c, degree=2)
    clf.fit(X_train, y_train)
    y_pred = clf.predict(X_test)
    sklearn_acc[c][kernel] = accuracy_score(y_test, y_pred)

Number of samples:  3220  Number of features:  57
639 support vectors out of 3220 points
b:  -2.130886902921289
Number of samples:  3220  Number of features:  57
534 support vectors out of 3220 points
b:  -0.09704345582706825
Number of samples:  3220  Number of features:  57
2639 support vectors out of 3220 points
b:  -0.2742826191975925
Number of samples:  3220  Number of features:  57
618 support vectors out of 3220 points
b:  -4.440883635473591
Number of samples:  3220  Number of features:  57
504 support vectors out of 3220 points
b:  -0.02596049767809162
Number of samples:  3220  Number of features:  57
2608 support vectors out of 3220 points
b:  -0.21494059840855612
Number of samples:  3220  Number of features:  57
856 support vectors out of 3220 points
b:  -5.820057526067475
Number of samples:  3220  Number of features:  57

In [ ]:
model_acc

In [ ]:
sklearn_acc

In [ ]:
model_df = pd.DataFrame(model_acc)
print("Our model accuracies:")
model_df

Best Accuracy is achieved using Linear kernel with soft margin(C) of 100.

In [ ]:
sk_df = pd.DataFrame(sklearn_acc)
print("Sklearn model accuracies:")
sk_df

## Visualization

a. Consider the model (with best hyper-parameters) and plot the decision boundary and the support vectors, on both train & test set.

In [ ]:
def make_meshgrid(x, y, h=.02):
    x_min, x_max = x.min() - 1, x.max() + 1
    y_min, y_max = y.min() - 1, y.max() + 1
    xx, yy = np.meshgrid(np.arange(x_min, x_max, h), np.arange(y_min, y_max, h))
    return xx, yy

In [ ]:
pca = PCA(n_components = None)
dfx_pca = pca.fit(X_train)

In [ ]:
plt.figure(figsize=(20,5))
plt.scatter(x=[i+1 for i in range(len(dfx_pca.explained_variance_ratio_))],
            y=dfx_pca.explained_variance_ratio_,
            s=200, alpha=0.75, c='red', edgecolor='m')
plt.grid(True)
plt.title('Explained variance ratio of the \nfitted principal component vector\n',fontsize=22)
plt.xlabel('Principal Components', fontsize=15)
plt.xticks([i+1 for i in range(len(dfx_pca.explained_variance_ratio_))], fontsize=13)
plt.yticks(fontsize=15)
plt.ylabel('Variance ratio', fontsize=15)
plt.show()

In [ ]:
def plot_contours(ax, clf, xx, yy, **params):
    Z = clf.predict(np.c_[xx.ravel(), yy.ravel()])
    Z = Z.reshape(xx.shape)
    out = ax.contourf(xx, yy, Z, **params)
    return out

In [ ]:
X_norm = (X-mean)/std

In [ ]:
pca = PCA(n_components=2)
Xreduced = pca.fit_transform(X_norm)
Xreduced

In [ ]:
X_train = Xreduced[:split_idx]
X_test = Xreduced[split_idx:]
y_train = y[:split_idx]
y_test = y[split_idx:]

In [ ]:
Xreduced = pd.DataFrame(data=Xreduced)
plt.figure(figsize=(20,10))
plt.scatter(X_test[0], X_test[1], c=pd.DataFrame(data=y_test), edgecolors='m', alpha=0.75, s=150)
plt.grid(True)
plt.title('Class seperation using first 2 principal components\n', fontsize=20)
plt.xlabel('PC-1', fontsize=13)
plt.ylabel("PC-2", fontsize=13)
plt.show()

In [ ]:
(X_train.shape,
y_train.shape)

In [ ]:
svmobj = SVM(C=100, kernel_type='linear')
svmobj.fit(X_train, y_train)

In [ ]:
fig, ax = plt.subplots()
# title for the plots
title = ('Decision surface of linear SVC ')
# Set-up grid for plotting.
X0, X1 = X_test[:, 0], X_test[:, 1]
xx, yy = make_meshgrid(X0, X1)

plot_contours(ax, svmobj, xx, yy, cmap=plt.cm.coolwarm, alpha=0.8)
ax.scatter(X0, X1, c=pd.DataFrame(data=y_test), s=20, edgecolors='m')
ax.set_ylabel('PC2')
ax.set_xlabel('PC1')
ax.set_xticks(())
ax.set_yticks(())
ax.set_title('Decison surface using the PCA transformed/projected features')
ax.legend()
plt.show()

In [ ]:
fig, ax = plt.subplots()
# title for the plots
title = ('Decision surface of linear SVC ')
# Set-up grid for plotting.
X0, X1 = X_train[:, 0], X_train[:, 1]
xx, yy = make_meshgrid(X0, X1)

plot_contours(ax, svmobj, xx, yy, cmap=plt.cm.coolwarm, alpha=0.8)
ax.scatter(X0, X1, c=y_train, s=20, edgecolors='m')
ax.set_ylabel('PC2')
ax.set_xlabel('PC1')
ax.set_xticks(())
ax.set_yticks(())
ax.set_title('Decison surface using the PCA transformed/projected features')
ax.legend()
plt.show()